CREATE TABLE Location (
    region_id integer NOT NULL,
    region_name text NOT NULL,
    location integer NOT NULL,
    location_name text NOT NULL,
    location_desc text NOT NULL,
    english_proficiency boolean NOT NULL,
    primary_lang text NOT NULL,
    currency text NOT NULL,
    ideal_season text NOT NULL,
    poi_1 text NOT NULL,
    poi_2 text NOT NULL,
    poi_3 text NOT NULL,
    url text NULL
);

INSERT INTO location VALUES(1,"Africa",1,"Botswana","Botswana is nothing short of enchanting! It’s home to incredible wildlife, breathtaking national parks, and intriguing local culture and history. It’s also one of the most popular destinations in Africa, especially for safaris!",t,"Setswana","Pula","Fall","Explore the Okavango Delta","See Meerkats at Jack's Camp","Vist Chobe National Park");
INSERT INTO location VALUES(1,"Africa",2,"Egypt","Between the Nile, the Red Sea, Alexandria, Cairo, and pyramids that date back to 2500 BC, Egypt offers so much history and culture.",t,"Masri","EGP","Spring","Visit the Egyptian Museum","Pyramids of Giza","Explore Alexandria");
INSERT INTO location VALUES(1,"Africa",3,"Kenya","Kenya is a country full of diverse landscapes and cultures, along with some unforgettable wildlife experiences. With endless plains that are full of wildlife, rolling hills, lush mountains, and a coastline that will leave you speechless, Kenya was made to explore!",t,"Swahili","KES","Summer","Witness the Great Migration","Stay at Giraffe Manor","Helicopter over Mount Kenya at sunrise");
INSERT INTO location VALUES(1,"Africa",4,"Mauritius","Mauritius is THE destination for a beach getaway offering palm-lined coastlines and water as clear as glass. This destination is for snorket fanatics and has a haven of dolphins and sea turtles. For land dwellers, hike a jungle trail to a waterfall, or just work on your tan.",t,"English","MUR","Winter","Colored Earth of Chamarel","Hike Le Morne Brabant","Go Snorkeling or Diving");
INSERT INTO location VALUES(1,"Africa",5,"Morocco","Morocco is a country that draws you in. From the colorful, heady markets filled with the rich scents of spices to the vibrant Atlas Mountains, there is just so much to see in this incredible North African country.",t,"Arabic","Dirham","Spring","Walk the streets of Marrakech","Visit Chefchaouen","Desert Glamping");
INSERT INTO location VALUES(1,"Africa",6,"South Africa","South Africa provides incredible opportunities for those who prefer the outdoor lifestyle. Additionally, this destination is packed with interesting people, hiking trails, horseback riding, plenty of beach space or getting lunch at a scenic restaurant.",t,"Zulu","Rand","Summer","Explore Cape Town","Road Trip the Cape Peninsula","Road Trip Across the Garden Route");
INSERT INTO location VALUES(2,"Asia",7,"Cambodia","Cambodia is a popular stop along the Southeast Asia backpacking route. The main attraction being the awe-inspiring ancient temples of Angkor Wat, located just outside of Siem Reap and known as the largest religious monument in the world.",f,"Khmer","KHR","Winter","Temples of Angkor Wat","Bayon Temple","Kampot");
INSERT INTO location VALUES(2,"Asia",8,"Indonesia","Indonesia offers over 17,800 islands including Bali, Komodo Island, Gili Islands, and more. Trek to the peak of the Kelimutu volcanic lake and scuba dive throughout the Gili Islands - Indonesia is a bucket list destination.",f,"Indonesian","IDR","Summer","Raja Ampat Islands","Bali","Komodo Island");
INSERT INTO location VALUES(2,"Asia",9,"Japan","From robot restaurants and Mario Karting in the streets to ancient temples and cat cafes, Japan blends its traditional and modern culture to provide tourists with an unforgettable experience. ",t,"Japanese","JPY","Spring","Must see Mount Fuji","Eat at a Robot Restaurant","Explore the Osaka Castle");
INSERT INTO location VALUES(2,"Asia",10,"The Maldives","Geographically surprising of 26 natural atolls, this island destination is known for providing the first accurate maritime charts of the Indian Ocean.",t,"Dhivehi","MVR","Winter","Snorkel at the Banana Reef","Male Market for souvenir shopping","Baros Island to zen out");
INSERT INTO location VALUES(2,"Asia",11,"Singapore","This thrilling city-state country is located off the tip of Malaysia. It boast a beautiful blend of culture including Malaysian, Indian, Chinese, Arab and English.",t,"Mandarin","SGD","All Year","A 158-year-old tropical oasis, the Singapore Botanic Gardens are a must see","Head to Chinatown for the epic Mid-Autumn Festival","Visit the historic neighborhood Joo Chiat!");
INSERT INTO location VALUES(2,"Asia",12,"Sri Lanka","Marco Polo visited Sri Lanka in the fourteenth centry and said it was undoubtedly the finest island in the world, and to this day it is one of the most beautiful travel destinations in the world",t,"Sinhala & Tamil","LKR","Winter","Visit Anuradhapura a UNESCO World Heritage cultural site","Climb to the top of Mihintale","Visit the stunning rock fortress Sigiriya");
INSERT INTO location VALUES(2,"Asia",13,"Thailand","A must for many travelers, Thailand offers unique experiences whether you came to view the majestic temples or indulge in the amazing food.",t,"Thai","THB","Winter","Chiang Mai Flower Festival","Bangkok","Sanctuary of Truth");
INSERT INTO location VALUES(2,"Asia",14,"Vietnam","Gorgeous landscapes, tasty food, and vibrant energy, Vietnam will take your breath away while giving you a full sensory experience. ",f,"Vietnamese","VND","All Year","Boat cruise Bai Tu Long Bay","Explore Saigon","Hanoi ");
INSERT INTO location VALUES(2,"Asia",15,"South Korea","South Korea is a highly developed country with its iconic pop cultural influences and is home of one of the worlds fastest internet connection speeds!",t,"Korean","won","Spring","Changdeokgung Palace","Busan","Seoraksan National Park");
INSERT INTO location VALUES(3,"Caribbean",16,"The Caribbean","This is where tropical island dreams come true. Each of the comprising 30 island territories that make up The Caribbean offer very unique experiences to all travelers. ",t,"Spanish","USD","Winter","Havana","Antigua","St Lucia");
INSERT INTO location VALUES(3,"Caribbean",17,"Aruba","Aruba is like no other. Its unique melting pot set in the middle of the Caribbean will definitely capture your heart.",t,"Papiamento","florin","Summer","Bubali Bird Sanctuary","Arikok National Park","Oranjestad");
INSERT INTO location VALUES(3,"Caribbean",18,"The Bahamas","The Bahamas is true paradise sprinkled with 700 islands over 100000 square miles of ocean.",t,"English","BSD","Winter","Nassau","Coral-reef diving in Sea of Abaco","Pig Beach");
INSERT INTO location VALUES(3,"Caribbean",19,"British Virgin Islands","The white sandy beaches and the world class sailing, makes the BVI a popular travel destination.",t,"English","USD","Fall","The Baths on Virgin Gorda","BVI Spring Regatta","Jost Van Dyke");
INSERT INTO location VALUES(3,"Caribbean",20,"Cuba","A unique blend of African, Spanish, and Caribbean influences, Cuba has some of the best food in the world.",t,"Spanish","CUP","Winter/Spring","Old Havana","Plaza Mayor","Museo Romantico");
INSERT INTO location VALUES(3,"Caribbean",21,"The Dominican Republic","Bordered by Haiti and the Caribbean, this country is known for its year round golf courses and is home to the Caribbean's tallest mountain peak, Pico Duarte.",t,"Spanish","DOP","Winter/Spring","Santo Domingo's Zona Colonial","Playa Dorada","Whale Watching in Samana Bay");
INSERT INTO location VALUES(4,"Central America",22,"Panama","The bridge between two continents, Panama is chalk full of history, wildlife, and adventure.",t,"Spanish","PAB","Winter","Panama City","Bocas Del Toro Scuba Diving","San Blas Islands");
INSERT INTO location VALUES(4,"Central America",23,"Honduras","The second largest country in Central America is home to reefs and rainforest but also has a history of being the murder capital of the world. ",t,"Spanish","HNL","Winter/Spring","Raotan, Bay Islands","Copan Ruins","Museum of Mayan Sculpture");
INSERT INTO location VALUES(4,"Central America",24,"Guatemala","From riding around on chicken buses to exploring the many historical sites, Guatamala is a true gem in Central America.",t,"Spanish","GTQ","Winter","Antigua","Lake Atitlan","Tikal in the Peten");
INSERT INTO location VALUES(4,"Central America",25,"Costa Rica","With jaw-dropping landscapes, friendly locals and jungle explorations, it's no wonder why touritsts flock to Costa Rica.",t,"Spanish","CRC","Winter","Envision Festival","Puerto Viejo","Arenal Volcano");
INSERT INTO location VALUES(4,"Central America",26,"Belize","Explore Mayan ruins and relax on picturesque beaches all in one trip! Belize has something for everyone!",t,"English","BZD","Winter","Actun Tunichil Muknal","Caracol","St. John's Cathedral");
INSERT INTO location VALUES(5,"Europe",27,"Austria","Welcome to the home of Mozart and Wienerschnitzel. From the moment you arrive in Austria, you will be taken back by the feeling you have stepped into a winter wonderland. ",t,"Austrian German","EUR","All Year","Krems","Melk","Vienna");
INSERT INTO location VALUES(5,"Europe",28,"Belgium","Belgium is a destination for the history buffs and chocolate lovers in our life.",t,"Dutch","EUR","All Year","Brussels","Bruges","Ghent");
INSERT INTO location VALUES(5,"Europe",29,"Croatia","The sea-to-table cuisine and fantastic wine make Croatia a food lovers paradise.",t,"Croatian","HRK","All Year","Plitvice National Park","Krka National Park","Istria");
INSERT INTO location VALUES(5,"Europe",30,"Czech Republic","Visiting the Czech Republic is a great starting point for any Eastern European trip.",t,"Czech","CZK","All Year","Prague","Kutna Hora","Karlovy Vary");
INSERT INTO location VALUES(5,"Europe",31,"Denmark","Often touted as the world's happiest country - it's not difficult to see why. ",t,"Danish","Krone","Spring/Summer/Fall","Bulbjerg Klint","Thy National Park","Rabjerg Mile");
INSERT INTO location VALUES(5,"Europe",32,"England","Ohh the history and iconic sites in England are quite spectacular. Whether you are a history buff or a Harry Potter fan, everyone can nerd out in England. ",t,"English","British Pound","All Year","London","Stonehenge","Buckingham Palace");
INSERT INTO location VALUES(5,"Europe",33,"France","When it comes to traveling, Paris seams to be one of the most sought after destinations and for good reason too. But don't let it steal all the limelight! France in general has alot to offer.",t,"French","EUR","All Year","Paris","Bordeaux","Corsica");
INSERT INTO location VALUES(5,"Europe",34,"Germany","With its long history and exceptional food, Germany is consider the heart of Europe",t,"German","EUR","All Year","Munich ","Berlin ","Frankfurt");
INSERT INTO location VALUES(5,"Europe",35,"Greece","If you want to leasure amongst the olive trees with a glass of wine than Greece is the country for you!",t,"Greek","EUR","Summer","Santorini","Athens","Thessoliniki");
INSERT INTO location VALUES(5,"Europe",36,"Iceland","Want to live out of a van for a few weeks and travel around? Well come to Iceland and begin your adventure!",t,"English","EUR","All Year","Blue Lagoon","Golden Circle","Reykjavik");
INSERT INTO location VALUES(5,"Europe",37,"Ireland","You can't get any greener than Ireland. Talk about craggy coastlines and lush meadows as far as the eye can see! Any traveler looking for a beer and a frolic would be happy in Ireland. ",t,"Gaelic","EUR","Spring/Summer/Fall","The Cliffs of Moher","Grafton Street, Dublin","Killarney National Park");
INSERT INTO location VALUES(5,"Europe",38,"Italy","If your looking for a ~Eat, Pray, Love~ experience, Italy is your go too.",t,"Italian","EUR","All Year","Florence","Pompeii","Rome");
INSERT INTO location VALUES(5,"Europe",39,"Malta","Malta has a laidback tropical vibe with picture perfect beaches and amazing diving.",t,"Maltese","EUR","All Year","Gjantija Temple","Mdina","Valletta");
INSERT INTO location VALUES(5,"Europe",40,"The Netherlands","A wonderland full of museums, quirky hotels, a buzzing food scene, and photogenic spots at every corner, The Netherlands is a country of style and adventure",t,"Dutch","EUR","All Year","Amsterdam","Hull","RotterDam");
INSERT INTO location VALUES(5,"Europe",41,"Poland","While parts of the country do still feel like a time warp, today's Poland also has a vibrant urbanity, enticing food and design culture, dynamic history, and kindhearted natives.",t,"Polish","PLN","Spring/Fall","Wroclaw","Warsaw","Cracow");
INSERT INTO location VALUES(5,"Europe",42,"Portugal","Portugal offers the pleasure of having white sandy beaches, beautiful cities, and rugged coastlines.",t,"Portuguese","EUR","Spring/Fall","Aveiro","Lisbon","Porto");
INSERT INTO location VALUES(5,"Europe",43,"Scotland","Scotland is known for its picturesque landscapes, jovial people, and booze!",t,"Gaelic","EUR","Spring/Fall","Edinburgh","Glasgow","Inverness");
INSERT INTO location VALUES(5,"Europe",44,"Spain","Spain is known for its festivals, beaches, and of course nigthlife!",t,"Spanish","EUR","Summer/Fall","Barcelona","Canary Islands","Granada");
INSERT INTO location VALUES(5,"Europe",45,"Sweden","Sweden is simply a jaw dropper. With its beautiful lakes, dense forests, and snow-capped mountains, it is a must for all travelers to experience!",t,"Swedish","SEK","Summer","Gothenburg","Lilla Korno","Stockholm");
INSERT INTO location VALUES(5,"Europe",46,"Switzerland","Chocolate and cheese. Sprinkle in some snow covered mountains and crystal clear lakes. Do I need to say anymore? ",t,"Swiss German, Swiss French, Swiss Italian","CHF","Spring/Fall","The Matterhorn ","Jungfraujoch: The Top of Europe","Interlaken");
INSERT INTO location VALUES(6,"The Middle East",47,"Egypt","With a rich history and an exotic culture, Egypt is full of unspoken treausures that the adventurous travel should experience. ",t,"Arabic","EGP","Fall/Winter/Spring","Pyramids of Giza","Coptic Cairo","Egyptian Museum of Antiquities");
INSERT INTO location VALUES(6,"The Middle East",48,"Jordan","Jordan is a diverse country with lots to explore and experience!",t,"Arabic","JOD","Spring/Fall","Amman","Dead Sea","Petra");
INSERT INTO location VALUES(6,"The Middle East",49,"Turkey","Visiting Turkey is one of the easiest, safest, and most fascinating ways to explore the Islamic culture.",t,"Turkish","TRY","Spring/Summer/Fall","Istanbul","Fairy chimneys","Pamukkale");
INSERT INTO location VALUES(6,"The Middle East",50,"United Arab Emirates","This city-state country has the perfect combination between modern/traditional and desert/sea.",t,"Arabic","AED","Fall/Winter/Spring","Burj Khalifa","Sheikh Zayed Mosque","Hajar Mountains");
INSERT INTO location VALUES(7,"North America",51,"Canada","Oh Canada! Your people and maple sugar always tends to leave travelers with a smile on their face.",t,"French/English","CAD","Summer/Fall","Banff","Montreal","Whistler");
INSERT INTO location VALUES(7,"North America",52,"Mexico","From lively music and vibrant colors, Mexico will keep you dancing through your stay.",t,"Spanish","MXN","All Year","Oaxaca","Tulum","Cozumel");
INSERT INTO location VALUES(7,"North America",53,"Puerto Rico","In Puerto Rico you may find yourself wandering the streets of Old San Juan or splashing around on the crystal clear beaches.",t,"Spanish","USD","Spring","Bioluminescent Bay","San Juan","Flamenco Beach");
INSERT INTO location VALUES(7,"North America",54,"New York City","From the Empire State Building to The Statue of Liberty to the endless brunch spots. NYC has it all.",t,"English","USD","Spring/Summer/Fall","Central Park","Statue of Liberty","Empire State Building");
INSERT INTO location VALUES(7,"North America",55,"Chicago","The Windy City has lots to see. From the Chicago Bean to the Sears Tower, this city has some magnificient architecture that will captivate any traveler.",t,"English","USD","Spring/Summer/Fall","Navy Pier ","The Shed Aquarium","Sears Tower");
INSERT INTO location VALUES(7,"North America",56,"Los Angeles","LA is a sprawling city that is home to sun-kissed beaches, laidback neighborhoods and fancy Tinseltown.",t,"English","USD","All Year","Universal Studios Hollywood","Old Town Pasadena","Sunset Boulevard");
INSERT INTO location VALUES(7,"North America",57,"San Francisco","San Fran means mild climate all year round. With temps always staying around 70 who wouldn't want to visit here?",t,"English","USD","All Year","Golden Gate Bridge","Alcatraz","Expore Haight-Ashbury");
INSERT INTO location VALUES(7,"North America",58,"Australia","Welcome downunder! Where kangaroos hop wildly and tourists rome freely.",t,"English","USD","All Year","Art & Museums in Melbourne","Brisbane","Sydney");
INSERT INTO location VALUES(7,"North America",59,"French Polynesia","With diverse marine life, French Polynesia boasts some of the most sought after diving in the world!",t,"French","CFP","Summer","Bora Bora","Rangiroa","Tahiti");
INSERT INTO location VALUES(7,"North America",60,"New Zealand","Backpacking New Zealand has changed my life. It was so easy to find work and good company here. Not to mention breath taking views!",t,"English","NZD","All Year","Milford Sounds","Tauranga","Coromandel Peninsula");
INSERT INTO location VALUES(8,"South America",61,"Bolivia","Bolivia is one-of-a-kind. Dubbed a country of extremes, Bolivia offers a rainbow of climates to the true explorer.",t,"Spanish","BOB","Summer/Fall","La Paz","Death Road","Uyuni Salt Flats");
INSERT INTO location VALUES(8,"South America",62,"Brazil","Brazil covers around half of South America. This makes it the largest country in South America. So its no surprise that it offers alot of diverse experiences and a rainbow of different geographicaly features. ",t,"Portuguese","BRL","All Year","Rio de Janeiro","Fernando de Noronha","Foz de Iguacu falls");
INSERT INTO location VALUES(8,"South America",63,"Colombia","Colombia. Not only is it the second most populated country in South America, but it is also home to a whopping 10% of the worlds biodiversity.",t,"Spanish","COP","Winter","Bogota","Guadalupe","Tayrona Naitonal Park");
INSERT INTO location VALUES(8,"South America",64,"Ecuador","Named after the equator that runs through it, this little Andean country it well known as one of the inspirations for Darwin's theory of evolution. ",t,"Spanish","USD","All Year","Galapagos Islands","Tungurahua Volcanoe","Quito");
INSERT INTO location VALUES(8,"South America",65,"Peru","Peru is home to natural wonders such as the Amazon, Lake titicaca, and Rainbow Mountain.",t,"Spanish","PEN","All Year","Inca Trail","Machu Picchu","Cusco");
INSERT INTO location VALUES(8,"South America",66,"Chile","Chile is the richest nation in South America and leads Latin America in peace, income per capita, and democratic development.",t,"Spanish","CLP","All Year","Santiago","Torres del Paine National Park","Easter Island");