# Generated by Django 3.1.2 on 2020-11-04 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20201103_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
        ),
        migrations.AlterField(
            model_name='author',
            name='imageURL',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_image'),
        ),
        migrations.AlterField(
            model_name='author',
            name='joined_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
