# Generated by Django 3.1.2 on 2020-11-12 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_auto_20201105_2326'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_id', models.IntegerField(default='', null=True)),
                ('region_name', models.CharField(max_length=100, null=True)),
                ('location', models.IntegerField(default='', null=True, unique=True)),
                ('location_name', models.CharField(max_length=100, null=True)),
                ('location_desc', models.CharField(max_length=1000, null=True)),
                ('english_proficiency', models.BooleanField(default='', null=True)),
                ('primary_lang', models.CharField(max_length=50, null=True)),
                ('currency', models.CharField(max_length=20, null=True)),
                ('ideal_season', models.CharField(max_length=20, null=True)),
                ('poi_1', models.CharField(max_length=500, null=True)),
                ('poi_2', models.CharField(max_length=500, null=True)),
                ('poi_3', models.CharField(max_length=500, null=True)),
                ('url', models.URLField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='author',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.location'),
        ),
    ]
