# Generated by Django 3.1.2 on 2020-11-13 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201112_2347'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.location'),
        ),
    ]
